---
name: Tests runner
description: Unit and integration tests runner for multiple compiler types.
author: PubNub
inputs:
  os:
    description: Environment in which framework should be built.
    required: true
  version:
    description: "Which version of 'cgreen' should be built."
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull Unit Test framework ('${{ inputs.os }}' gcc, clang)
      uses: ./.github/workflows/composite/unit-test-framework
      with:
        os: ${{ inputs.os }}
        version: ${{ inputs.version }}
        compilers: gcc,clang
    - name: Prepare Unit Test framework ('${{ inputs.os }}' gcc)
      shell: bash
      run: |
        mv "$GITHUB_WORKSPACE/cgreen" "$GITHUB_WORKSPACE/cgreen-universal"
        cp -r "$GITHUB_WORKSPACE/cgreen-universal/gcc" "$GITHUB_WORKSPACE/cgreen"
    - name: Run unit tests ('${{ inputs.os }}' gcc)
      shell: bash
      env:
        CC: gcc
        CXX: "g++"
      run: |
        echo "::group::Run unit tests ('${{ inputs.os }}' gcc)"
        cd "$GITHUB_WORKSPACE/core"
        make clean generate_report
        cd "$GITHUB_WORKSPACE/lib"
        make clean generate_report
        echo "::endgroup::"
    - name: Run integration tests ('${{ inputs.os }}' gcc)
      shell: bash
      env:
        CC: gcc
        CXX: "g++"
      run: |
        echo "::group::Run integration tests ('${{ inputs.os }}' gcc)"
        cd "$GITHUB_WORKSPACE"
        make -f posix.mk clean all
        posix/pubnub_fntest
        openssl/pubnub_fntest
        cpp/fntest_runner
        cpp/openssl/fntest_runner
        echo "::endgroup::"
    - name: Prepare Unit Test framework ('${{ inputs.os }}' clang)
      shell: bash
      run: |
        rm -rf "$GITHUB_WORKSPACE/cgreen"
        cp -r "$GITHUB_WORKSPACE/cgreen-universal/clang" "$GITHUB_WORKSPACE/cgreen"
    - name: Run unit tests ('${{ inputs.os }}' clang)
      shell: bash
      env:
        CC: clang
        CXX: "clang++"
      run: |
        echo "::group::Run unit tests ('${{ inputs.os }}' clang)"
        cd "$GITHUB_WORKSPACE/core"
        make clean generate_report
        cd "$GITHUB_WORKSPACE/lib"
        make clean generate_report
        echo "::endgroup::"
    - name: Run integration tests ('${{ inputs.os }}' clang)
      shell: bash
      env:
        CC: clang
        CXX: "clang++"
      run: |
        echo "::group::Run integration tests ('${{ inputs.os }}' clang)"
        cd "$GITHUB_WORKSPACE"
        make -f posix.mk clean all
        posix/pubnub_fntest
        openssl/pubnub_fntest
        cpp/fntest_runner
        cpp/openssl/fntest_runner
        echo "::endgroup::"
    - name: Restore Unit Test framework ('${{ inputs.os }}' gcc,clang)
      shell: bash
      run: |
        rm -rf "$GITHUB_WORKSPACE/cgreen"
        cp -r "$GITHUB_WORKSPACE/cgreen-universal" "$GITHUB_WORKSPACE/cgreen"