
name: run_acceptance_tests

on: [push]

jobs:
  build:
    name: Perform Acceptance BDD tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup environment
        run: |
          sudo apt-get install -y ninja-build libboost-all-dev libssl-dev
          sudo gem install cucumber
      - name: Git clone cucumber-cpp
        run: |
          git clone https://github.com/cucumber/cucumber-cpp.git
      - name: Cache cucumber-cpp
        id: cache-cucumber-cpp
        uses: actions/cache@v2
        with:
          path: |
            cucumber-cpp
          key: ${{ runner.os }}-cucumber-cpp-${{ hashFiles('cucumber-cpp/**') }}
          restore-keys: |
              ${{ runner.os }}-cucumber-cpp
      - name: Configure cucumber-cpp
        if: steps.cache-cucumber-cpp.outputs.cache-hit != 'true'
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
        working-directory: ./cucumber-cpp

      - name: Build cucumber-cpp
        if: steps.cache-cucumber-cpp.outputs.cache-hit != 'true'
        run: |
          cmake --build build --config Debug
        working-directory: ./cucumber-cpp
     
      - name: Build acceptance tests
        run: |
          cd cpp
          make -f posix_openssl.mk openssl/pubnub_sync
          cd ..
          g++ -std=c++11 -g -o BoostSteps.o -c features/step_definitions/BoostSteps.cpp -Icucumber-cpp/include -Icucumber-cpp/build/src/ -Iposix -Icore -I. -Icpp -D PUBNUB_CRYPTO_API=1 -D PUBNUB_USE_SSL=0
          g++ -o steps BoostSteps.o cpp/pubnub_sync.a cucumber-cpp/build/src/libcucumber-cpp.a -Lboost -lboost_unit_test_framework -lpthread -lboost_regex -lboost_thread -lboost_program_options -lboost_filesystem -lssl -lcrypto -D PUBNUB_USE_SSL=0
      - name: Run acceptance tests
        env:
          PAM_PUB_KEY: "pub_key"
          PAM_SUB_KEY: "sub_key"
          PAM_SEC_KEY: "sec_key"
        run: |
          mv sdk-specifications/features/access features
          sudo python3 run_contract_tests.py features/access/grant-token.feature
          ls -la results
      - name: Upload acceptance tests reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: acceptance-test-reports
          path: ./results/**
